### ISSUE TITLE
Class inheritance diagram hard to read in dark mode

### ISSUE THREAD

**Issue by pllim** [astropy/sphinx-automodapi#167]
### Light mode 😄 

<img width="387" alt="Screenshot 2023-05-24 235452" src="https://github.com/astropy/sphinx-automodapi/assets/2090236/13a1a7db-8a4a-47c2-b1e4-52fc493af711">

### Dark mode 😭 

<img width="391" alt="Screenshot 2023-05-24 235427" src="https://github.com/astropy/sphinx-automodapi/assets/2090236/102166d6-b21e-45c1-8276-a3ffcf3e2e88">

<hr/>

xref https://github.com/astropy/astropy/pull/14867

**Comment by Cadair** [comment]
Isn't this actually a sphinx issue? as sphinx generates the diagram not us?

**Comment by Cadair** [comment]
heh no.

**Comment by eteq** [comment]
I'm pretty confident this is a hybrid problem.  Unless it's been changed since I last looked, sphinx makes these inheritance diagrams with graphviz. In principle it's easy to change the styling as a result since it's graphviz.   But what we might want to do is play with it in `Automoddiagram` first, and then if we can get something that looks good in both dark and light mode we can try it there, and then try to push it upstream in sphinx.

Another option is to bypass it entirely and instead just invert the colors  in the sphinx theme - I think this is a simple matter of putting a CSS along the lines of the below in the right spot to get triggered by dark mode (or maybe a little javascript snippet that does the same thing). That feels a bit hackier but might be safer if the color scheme is to hard to get right?

```
img {
   -webkit-filter: invert(1);
   filter: invert(1);
   }
```

**Comment by Cadair** [comment]
I did something inspired by this for the sunpy theme rewrite and it comes out *ok*:

![image](https://github.com/astropy/sphinx-automodapi/assets/1391051/2a3b76bf-675a-4a56-817f-ceb9092e4caa)

The CSS was:

```css
/* Flip the colours on graphviz graphs on dark mode */
html[data-theme="dark"] div.graphviz > object.inheritance {
  filter: invert(1);
}
```

**Comment by Cadair** [comment]
I would probably say either astropy or sphinx-astropy.
