### ISSUE TITLE
Problem rendering inheritance diagram 

### ISSUE THREAD

**Issue by appukuttan-shailesh** [astropy/sphinx-automodapi#98]
Previously my docs used to properly render the inheritance diagram, such as in here:
![image](https://user-images.githubusercontent.com/24866517/78681917-a049e100-78ed-11ea-9555-85c0b52a20c9.png)

(source: https://demounit.readthedocs.io/en/latest/page_tests.html)

But today when I cloned my repo and compiled the docs, I get the following instead of the inheritance diagram:
![image](https://user-images.githubusercontent.com/24866517/78681779-74c6f680-78ed-11ea-84bf-c0c3ab305e98.png)

Any idea what is going wrong? I tested the same on a completely different project repository, and there I too had the same result.

**Comment by MarineChap** [comment]
Same problem here. If someone come up with a solution, I am interested in. 
Note: I have a correct display when building local, but not once the documentation is only. 
Could be a navigator problem? I tried with Firefox and Chrome with the same bad result.

**Comment by appukuttan-shailesh** [comment]
Today I recompiled the docs on ReadTheDocs (RTD), and the inheritance diagram came out correctly:
[see here](https://hippounit.readthedocs.io/page_tests.html)

I faced the original problem when running locally. I haven't yet had a chance to investigate this more closely (like the package combinations on local vs RTD), but if it's useful for @MarineChap  or anyone else, here is the build log of my successful attempt on RTD this morning:
https://readthedocs.org/projects/hippounit/builds/10798752/

Do update here if something comes out of it.

**Comment by MarineChap** [comment]
Thanks for your feedback. For my case, it has been "fixed" because I had forget to add the graphviz module in my bitbucket pipeline (while I had this module in my local environment). 
But I still have a problem of rendering because instead of a the text in the graph I have only little square. Probably a font problem installed system-wide in my linux but not in the bitbucket pipeline. I will open a separate issue for this. 
Therefore from my point of view, this issue can be closed. :)

**Comment by appukuttan-shailesh** [comment]
Thanks for the update. It works for me online (ReadTheDocs), so this isn't much of a problem for me anymore. Will check if locally graphviz was missing for me. Thanks again.

**Comment by MarineChap** [comment]
Thanks for your feedback. For my case, it has been "fixed" because I had forget to add the graphviz module in my bitbucket pipeline (while I had this module in my local environment). 
But I still have a problem of rendering because instead of a the text in the graph I have only little square. Probably a font problem installed system-wide in my linux but not in the bitbucket pipeline. I will open a separate issue for this. 
Therefore from my point of view, this issue can be closed. :)
